package mx.com.aforecoppel.registromovilguardardatos.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2022-01-05T10:35:46.270-07:00
 * Generated source version: 3.4.1
 *
 */
@WebService(targetNamespace = "https://www.aforecoppel.com.mx/NotificarRegistroMovil/", name = "NotificarRegistroMovilPort")
@XmlSeeAlso({mx.com.aforecoppel.registromovilguardardatos.jaxb.ObjectFactory.class, mx.com.aforecoppel.registromovilguardardatos.notificarregistromoviltypes.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NotificarRegistroMovilPort {

    @WebMethod(action = "https://www.aforecoppel.com.mx/NotificarRegistroMovil/notificarRegistroMovil/")
    @WebResult(name = "notificarRegistroMovilResponse", targetNamespace = "https://www.aforecoppel.com.mx/NotificarRegistroMovil/notificarRegistroMovil/", partName = "notificarRegistroMovilResponse")
    public mx.com.aforecoppel.registromovilguardardatos.jaxb.NotificarRegistroMovilRespuesta notificarRegistroMovil(

        @WebParam(partName = "notificarRegistroMovilRequest", name = "notificarRegistroMovilRequest", targetNamespace = "https://www.aforecoppel.com.mx/NotificarRegistroMovil/notificarRegistroMovil/")
        mx.com.aforecoppel.registromovilguardardatos.jaxb.NotificarRegistroMovilContrato notificarRegistroMovilRequest
    );
}
