package mx.com.aforecoppel.registromovilguardardatos.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2022-01-05T10:35:46.332-07:00
 * Generated source version: 3.4.1
 *
 */
@WebServiceClient(name = "NotificarRegistroMovil",
                  wsdlLocation = "file:/C:/Users/afore.asanchezf/Desktop/wsregistromovilguardardatos/src/main/resources/wsdl/NotificarRegistroMovil.wsdl",
                  targetNamespace = "https://www.aforecoppel.com.mx/NotificarRegistroMovil/")
public class NotificarRegistroMovil extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://www.aforecoppel.com.mx/NotificarRegistroMovil/", "NotificarRegistroMovil");
    public final static QName NotificarRegistroMovilPort = new QName("https://www.aforecoppel.com.mx/NotificarRegistroMovil/", "NotificarRegistroMovilPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/afore.asanchezf/Desktop/wsregistromovilguardardatos/src/main/resources/wsdl/NotificarRegistroMovil.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NotificarRegistroMovil.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/afore.asanchezf/Desktop/wsregistromovilguardardatos/src/main/resources/wsdl/NotificarRegistroMovil.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NotificarRegistroMovil(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotificarRegistroMovil(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificarRegistroMovil() {
        super(WSDL_LOCATION, SERVICE);
    }

    public NotificarRegistroMovil(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NotificarRegistroMovil(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NotificarRegistroMovil(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns NotificarRegistroMovilPort
     */
    @WebEndpoint(name = "NotificarRegistroMovilPort")
    public NotificarRegistroMovilPort getNotificarRegistroMovilPort() {
        return super.getPort(NotificarRegistroMovilPort, NotificarRegistroMovilPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificarRegistroMovilPort
     */
    @WebEndpoint(name = "NotificarRegistroMovilPort")
    public NotificarRegistroMovilPort getNotificarRegistroMovilPort(WebServiceFeature... features) {
        return super.getPort(NotificarRegistroMovilPort, NotificarRegistroMovilPort.class, features);
    }

}
